### ISSUE TITLE
Is there some scenario where the embeddings are not initially stored on flair.device?

### ISSUE THREAD

**Issue by pommedeterresautee** [zalandoresearch/flair#1104]
From token class:

```python
    def set_embedding(self, name: str, vector: torch.tensor):
        device = flair.device
        if len(self._embeddings.keys()) > 0:
            device = next(iter(self._embeddings.values())).device
        if device != vector.device:
            vector = vector.to(device)
        self._embeddings[name] = vector
```
What is the purpose of the following line?
```python
            device = next(iter(self._embeddings.values())).device
```
I understand it means that if for a token the first representation is on a different device than flair.device, then set put the new embedding on the same device.

What I don't understand is why it would happen?

**Comment by alanakbik** [comment]
Hi @pommedeterresautee yes that can happen if you mix dynamic and static embeddings, train on gpu and use `embedding_storage_mode='cpu'` (because all embeddings of the corpus do not fit into cuda memory). 

In this case, in epoch 1 static embeddings are generated on cuda memory but then moved to cpu memory at the end of each mini-batch. However, dynamic embeddings are always deleted after use, so in epoch 2, new dynamic embeddings are generated on gpu, whereas the static embeddings of the previous epoch are stored in cpu memory. If we didn't do this check, the dynamic and static embeddings would be on different devices and the `torch.cat` in `get_embedding()` would fail.
