### ISSUE TITLE
Anu embeddings based on syntactic dependency?

### ISSUE THREAD

**Issue by ristonen** [zalandoresearch/flair#1123]
Hi!

Does flair have or have anyone heard of embeddings based on syntactic dependency? What I mean is that the embedding would not check a previous word but instead the head word.

Check two of the first pictures from here:
https://www.ling.upenn.edu/~ceolin/Dependency_Parsing.html

I have Turku NLP parser that gives me the head words (that the word is dependant to) for all words in the sentence and I would like to use this info for embedding. For surely it must be more powerful that just the previous word / next word. Finnish is my language.

OR: If there is no embedding, could I somehow rearrange the words in sentences and use forward or backward embeddings? The problem in this is that same word can be head word to many words in sentence. Any ideas? :)

Thanks for all input! <3

**Comment by alanakbik** [comment]
Hello @ristonen yes several such embeddings exist. For English, we packaged the embeddings by [Komninos et al.](http://www-users.cs.york.ac.uk/~suresh/papers/dep_embeddings_naacl2016.pdf), you can load them like this: 
```python
embeddings = WordEmbeddings('extvec')
```
For Finnish we don't have precomputed dependency word embeddings. You could follow their approach to generate your own, or use the Finnish `FlairEmbeddings` which might work very well since Finnish has very rich morphology and character approaches tend to work well here. For instance, you could try the following embedding stack: 

```python
finnish_embeddings = StackedEmbeddings([
                                        BytePairEmbeddings('fi'),
                                        FlairEmbeddings('fi-forward'),
                                        FlairEmbeddings('fi-backward'),
                                       ])
```

**Comment by ristonen** [comment]
Big Thanks, I’ll check that!
