### ISSUE TITLE
Error while using XLNet and RoBERTa embeddings but work fine with BERT embeddings

### ISSUE THREAD

**Issue by isarth** [zalandoresearch/flair#1221]
**Describe the bug**
While training custom NER model using LSTM with CRF. The model works fine with BERT and glove but gives an error with XLNet and Roberta embeddings. 

  File "/home/rajivratn/miniconda3/envs/sarthak_new/lib/python3.6/site-packages/flair/embeddings.py", line 1116, in _get_transformer_sentence_embeddings
    use_scalar_mix=use_scalar_mix,
  File "/home/rajivratn/miniconda3/envs/sarthak_new/lib/python3.6/site-packages/flair/embeddings.py", line 975, in _extract_embeddings
    first_embedding: torch.FloatTensor = current_embeddings[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

Environment (please complete the following information):
- Ubuntu 
 - Version 0.4.3

**Comment by stefan-it** [comment]
Could you provide a code snippet for reproducing the error? What dataset do you use 🤔

**Comment by Hellisotherpeople** [comment]
I am also having these exact errors, not sure what's going on.

**Comment by 0x7A31C7** [comment]
I got the same error while using `XLNetEmbeddings`. In my case, the issue was with some of the unicode characters. 

For example, `XLNetTokenizer` returns an empty list for the unicode character `˜` (U+02DC). This means that the length of subwords for the corresponding token in `token_subwords_mapping` is zero (see function [_build_token_subwords_mapping](https://github.com/zalandoresearch/flair/blob/b8e68ae1a147ee9e8700d63fbc9528cf63fd1d58/flair/embeddings.py#L1078)). 

This is problematic when evaluating `current_embeddings` in function [_extract_embeddings](https://github.com/zalandoresearch/flair/blob/b8e68ae1a147ee9e8700d63fbc9528cf63fd1d58/flair/embeddings.py#L1026), because now you get an empty Tensor and an exception is thrown when you try to index it.

**Comment by stefan-it** [comment]
@0x7A31C7 I'll check it again :) I think that we can use the `unk_token` symbol whenever the tokenizer returns an empy token list.

**Comment by stefan-it** [comment]
Similar issues was raised in `transformers` today: https://github.com/huggingface/transformers/issues/1662

**Comment by isarth** [comment]
Is there a fix ?

**Comment by isarth** [comment]
> @0x7A31C7 I'll check it again :) I think that we can use the `unk_token` symbol whenever the tokenizer returns an empty token list in flair.

Where can I make this change?

**Comment by stefan-it** [comment]
@isarth Could you try to checkout the new `GH-1221-fix-tokenization-problems` branch? This should fix all tokenization problems by checking the subword length after tokenization. Whenever a tokenizer return a length of 0 (`˜` -> `` for the XLNetTokenizer) then the `unk_token`.
