### ISSUE TITLE
Preparing custom dataset for training

### ISSUE THREAD

**Issue by ermolushka** [zalandoresearch/flair#169]
In the docs, it's said that for training your model you need dataset in such format

`George N B-PER
Washington N I-PER
went V O
to P O
Washington N B-LOC`

Is it possible to prepare it with flair?

**Comment by alanakbik** [comment]
Hi @ermolushka - datasets are typically one word per row and one type of annotation per column, i.e.: 

```console
George N B-PER 
Washington N I-PER 
went V O 
to P O 
Washington N B-LOC
```

Most NLP sequence labeling datasets are already in such a format, although the columns differ. For this, you can define column names as described in the readme by passing a dict with numbers and names: 

```python
# define columns
columns = {0: 'text', 1: 'pos', 2: 'np'}
```

But if your data is in a completely different format, you either need to convert into such a column format or write your own data loader. There are no helpers for this yet, but if it makes sense for a specific format, we always appreciate contributions!

**Comment by ermolushka** [comment]
@alanakbik Thanks for your response. I think I'll contribute in near future, thanks!

**Comment by ermolushka** [comment]
@alanakbik One more question about preparing custom data. For example, If I want to get POS from nltk, I can get a list like this https://pythonprogramming.net/natural-language-toolkit-nltk-part-speech-tagging/

And in the flair docs, there are different POS like N, V, P. Do you have a list of all possible POS-tags?

**Comment by alanakbik** [comment]
@ermolushka The possible PoS tags always depend on the language and tagset that you use. For our pre-trained English model, we used the [Penn treebank PoS tags](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and for the German model the [Universal PoS tags](http://universaldependencies.org/u/pos/). We are planning to add more languages in the near future, and will then probably completely switch to Universal PoS tags since they are the same for all languages.
