### ISSUE TITLE
Training word level LM using FLAIR

### ISSUE THREAD

**Issue by omerarshad** [zalandoresearch/flair#201]
I have my own word embeddings, can i use flair to train a LM using my trained word embeddings?

**Comment by djstrong** [comment]
In LM you need a text. What is more, flair uses character LM, not word LM.

**Comment by omerarshad** [comment]
Can i use FLAIR to train word level LM? instead of character LM?

**Comment by djstrong** [comment]
Yes, `TextCorpus` has `character_level: bool = True`.

**Comment by omerarshad** [comment]
great, so my question was that is it possible to train word based LM, where word representation is taken from char LM?

**Comment by alanakbik** [comment]
Hi @omerarshad I think you might need to adapt the training method for this since now we are taking a dictionary of chars / words as one-hot-embeddings that are first embedded in an uninitialized embedding layer and then used during training. This could be a very interesting approach (use the character LM to train a stronger word-level LM), so if you decide to implement this in Flair, we'd be very curious to hear about your progress!
