### ISSUE TITLE
Do we need any preprocessing to train LM?

### ISSUE THREAD

**Issue by omerarshad** [zalandoresearch/flair#219]
hello.my text contains URLS, emojis and noise, do I need to remove them or is it okay to train on corpus as it is?

**Comment by alanakbik** [comment]
Hi @omerarshad - generally I would recommend using the corpus as-is, since if you do pre-processing you make the data less "real" than you would encounter in a use case. Especially if you train the LM on the character-level it does not make a big difference since URLS, emojis and others are just sequences of characters.

**Comment by omerarshad** [comment]
Great, Thanks

**Comment by qiuwei** [comment]
Hi, @alanakbik  could you explain why you randomly change the cases for the letters by a small portion? I am curious about the motivation. 
Thanks in advance!

**Comment by alanakbik** [comment]
Hi @qiuwei this is a data augmentation technique. By randomly upper and lowercasing sentences, we make the LM less dependent on capitalization as a feature, and thus (hopefully) more robust to sentences with irregular capitalization (such as social media text).
