### ISSUE TITLE
Getting IndexError: list index out of range error

### ISSUE THREAD

**Issue by Rishav09** [zalandoresearch/flair#233]
I am getting `Getting IndexError:list index out of range error` when I changed the `dev_file=None`
in 
 
          
    corpus: TaggedCorpus = NLPTaskDataFetcher.fetch_column_corpus(data_folder, columns,
                                                                  train_file='train.txt',
                                                                  test_file='test.txt',
                                                                   dev_file=None)

I am using custom dataset .
Also ,  What does __sample() method do in data_fetcher.py ?

**Comment by alanakbik** [comment]
Hi @Rishav09 the __sample() method samples a dev data set from the train data. I realize now that the way this method is implemented can throw an error on small datasets, since we fixed the sample to always sample the same sentence ids. But if the dataset is small, an id may not exist which throws the error. 

As a quick workaround for now, you could create a small dev dataset yourself and pass it to the method so that the error does not get thrown.

I think we need to fix this with a PR to change this method so that it does random sampling instead.

**Comment by Rishav09** [comment]
Thanks a lot...)

**Comment by Bilel-tn** [comment]
Hello, 
I am getting also an [IndexError : IndexError: list index out of range]. I am trying to train a model based using my own sequence labeling dataset (BIO annotation) imported from a text file.  Here is the code I use : 

```
# Define the training columns 
columns = {1 : 'text' , 2 : 'ner_tags' }
data_folder= 'data'
train_file='train.txt' 
corpusJURI: Corpus = ColumnCorpus(data_folder, columns, train_file , encoding='cp1252')
```
**I think the error is related to the encoding because the text in column 1 is in french, which implies special characters. When I select another column not containing french special characters, the error no longer exists.** 

Can you help me please (even though I know you get this question quiet often) ?
