### ISSUE TITLE
Text classification loads whole data once in memory?

### ISSUE THREAD

**Issue by omerarshad** [zalandoresearch/flair#273]
I have a huge data set aroung 4gb in size, when i load it using classification module, it  eats up my whole ram.. any work around for it?

**Comment by tabergma** [comment]
Hi @omerarshad, yes, we are loading the entire data set into memory for text classification and currently, we don't support any other way of loading the data set. If this is an issue that affects more people, we could include a solution to train on such large files. But for now, I guess the only possibility for you is to downsample the data. Sorry.

May I asked what kind of data set you are using. 4GB is really large.

**Comment by omerarshad** [comment]
Data is of some company, cant be shared. Downsampling will reduce training samples only?

**Comment by tabergma** [comment]
If you want to use our build in function `corpus.downsample()`, you can specify the percentage of data you want to keep and you can specify if you only want to downsample train or everything (see https://github.com/zalandoresearch/flair/blob/master/flair/data.py#L595).

For example, use
```
corpus.downsample(percentage = 0.5, only_downsample_train = True)
```
if you want to keep only half of the training data, but keep everything for test and dev.

However, keep in mind that in order to apply `downsample` you need to read the entire data set once. If you don't want that, you need to downsample the data by our own beforehand.

**Comment by omerarshad** [comment]
can i use data splits? e.g. 50 splits of trainig set?

**Comment by tabergma** [comment]
You could train the model in iterations following the approach mentioned here: https://github.com/zalandoresearch/flair/issues/225

**Comment by omerarshad** [comment]
can you write a small snipped which loads text classifier model? and will it append new labels to dictionary itself?

**Comment by tabergma** [comment]
For loading a text classifier simply execute
```
model = TextClassifier.load_from_file(model_file)
```
In release-0.4 we will also include a function to load a trainer together with the model, which makes it more handy to continue training of a model at a later point. 

You have to append new labels to the dictionary by yourself. You can do that with the following code snippet:
```
overall_label_dict = Dictionary(add_unk=False)
# load corpus
current_label_dict = corpus.make_label_dictionary()
for label in current_label_dict.get_items():
    overall_label_dict.add_item(label)
```
