### ISSUE TITLE
how to install flair in anaconda?

### ISSUE THREAD

**Issue by cerlymarco** [zalandoresearch/flair#330]
Is it possible to use flair with anaconda and jupyter? Thanks

**Comment by youngawesome** [comment]
You can use flair with anaconda and jupyter, just need  `pip install flair` .

**Comment by youngawesome** [comment]
> Is it possible to use flair with anaconda and jupyter? Thanks

You can use flair with anaconda and jupyter, just need pip install flair .

**Comment by cerlymarco** [comment]
> > Is it possible to use flair with anaconda and jupyter? Thanks
> 
> You can use flair with anaconda and jupyter, just need` pip install flair .`

i used pip but this message appear "Could not find a version that satisfies the requirement torch==1.0.0 (from flair) (from versions: 0.1.2, 0.1.2.post1) No matching distribution found for torch==1.0.0 (from flair)" (i have python 3.6 installed)

**Comment by davidalbertonogueira** [comment]
> I had an issue that jupyter **testpath** package didn't give permission to install **flair** . I tried a different approach to solve it. Only one way which worked for me it is deleting testpath, and installing flair, and installing testpath package again. Here the the step:
> 
> ```
> pip uninstall testpath
> pip install flair
> pip install testpath
> ```
> P.S : Please, don't judge strictly. I'm in the beginning of my way to become Data Scientist :)

Well, I have pytorch installed, and I have no testpath module to uninstall. 
I'm facing the same error (Could not find a version that satisfies the requirement torch==1.0.0 (from flair)) :/

**Comment by dduuu** [comment]
use this command for install flair "pip install flair --no-deps"

**Comment by maironcastro** [comment]
> > > Is it possible to use flair with anaconda and jupyter? Thanks
> > 
> > 
> > You can use flair with anaconda and jupyter, just need` pip install flair .`
> 
> i used pip but this message appear "Could not find a version that satisfies the requirement torch==1.0.0 (from flair) (from versions: 0.1.2, 0.1.2.post1) No matching distribution found for torch==1.0.0 (from flair)" (i have python 3.6 installed)

Maybe it's because you do not have a CUDA-capable system or do not require CUDA, as said in pythorch website. You should try:

# Python 2.7
pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl
pip install torchvision
# if the above command does not work, then you have python 2.7 UCS2, use this command
pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp27-cp27m-linux_x86_64.whl
# Python 3.5
pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp35-cp35m-linux_x86_64.whl
pip3 install torchvision
# Python 3.6
pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
pip3 install torchvision
# Python 3.7
pip3 install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
pip3 install torchvision

**Comment by schwartzadev** [comment]
[Here](https://pytorch.org/get-started/locally/)'s the info on the PyTorch website, with options to choose which OS you're installing onto, which Python version you're installing for, whether you want nightly builds, etc.
