### ISSUE TITLE
Error when training my flair embedding

### ISSUE THREAD

**Issue by xuxingya** [zalandoresearch/flair#344]
I am training my flair character embedding following the Tutorial 9 using a Chinese corpus. Everything went well until an error occurred at the end of split 3 epoch 2. 

> RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry = infinity or NaN) at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:302

Here is the screen shot:
![image](https://user-images.githubusercontent.com/13343428/50571321-7c424a80-0de2-11e9-9d23-c03aed95560e.png)

It looks like some rows of  'word_weights' happened to be NaN or infinity. But it takes too much time to reproduce the problem. I just used the code in Tutorial 9 to create my vocab.

My system is Ubuntu18, Python3, with torch 1.0.0.

**Comment by alanakbik** [comment]
Hi, yes this problem happens during text generation at the end of each epoch. It occurs more commonly in languages with large character vocabularies such as Chinese. 

It is fixed in the master branch (see #322). We will also push a new version to pip soon that includes this fix. Until then to avoid this problem you would need to checkout the master branch and train on this branch instead of the installed flair.

**Comment by zsn6034** [comment]
thanks! I will try.

> Hi, yes this problem happens during text generation at the end of each epoch. It occurs more commonly in languages with large character vocabularies such as Chinese.
> 
> It is fixed in the master branch (see #322). We will also push a new version to pip soon that includes this fix. Until then to avoid this problem you would need to checkout the master branch and train on this branch instead of the installed flair.

**Comment by zsn6034** [comment]
I haven' try it. I found if the parameters changed, the model can work and no error, so I no install new one.
