### ISSUE TITLE
Reproduce Experiments on CoNLL2003 English NER 

### ISSUE THREAD

**Issue by HAWLYQ** [zalandoresearch/flair#416]
A clear and concise description of what you want to know.
Hi, @alanakbik, I ran the reproduce code showed in https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md  5 times and  the mean f1 is 92.76, which is lower than reported 93.07. Could you give me some suggestions?  The language models I used are lm-news-english-backward-v0.2rc.pt and lm-news-english-forward-v0.2rc.pt.  This is one of my training log files.
[conll_flair_reproduce5.log](https://github.com/zalandoresearch/flair/files/2785451/conll_flair_reproduce5.log)
(The patience you set in your code is ‘’3‘’, which is inconsistent with the ‘’5‘’ written in paper, but I think this is not the main problem)

**Comment by alanakbik** [comment]
Hi @HAWLYQ thanks for reporting this - since a lot of things have changed since the original Flair release (e.g. bug fixes #184 #390 etc., changes #48 #270 etc.), I am currently re-doing all experiments to compute updated numbers and updated instructions on how to reproduce (old instructions only apply for Flair 0.2). I think everything will be done next week, so we can push everything with the 0.4.1 release!

**Comment by stefan-it** [comment]
I did two runs for CoNLL2003 using the latest version of `flair`. I could only get 0.9264 (patience 5) and 0.9266 (patience 3).

**Comment by HAWLYQ** [comment]
@alanakbik ， thanks for your kind reply and  work.  I am looking forward  to the 0.4.1 release!

**Comment by yahshibu** [comment]
Hello, thank you for your contributions to the NLP community!

I was expecting that the 0.4.1 would be released last week. Will it take more time?
I'm thinking of using Flair embeddings for my work... (although it's self-centered...)

**Comment by alanakbik** [comment]
Flair 0.4.1 is out, we also updated the experiments description!
