### ISSUE TITLE
Iterating data fetcher for very large datasets

### ISSUE THREAD

**Issue by KobeDeShow** [zalandoresearch/flair#426]
I had 100 million samples,  when i used  data_fetcher.load_column_corpus api,  it costed 100G memory!   how can i fix this problem?

**Comment by alanakbik** [comment]
Hi @KobeDeShow thanks for raising this. The problem is that our current implementation loads the entire data set into memory, which will not work well for data sets of this size. This is something we have been meaning to find a better solution for, but don't yet know exactly how to best address this.

One idea would be to use some sort of iterator or the DataLoader API as was recently added to the `LanguageModelTrainer` (master branch).

I'll add a 'feature' tag to this issue - this is something we need to look into. As always, any suggestions/ideas from the community would be greatly appreciated :)
