### ISSUE TITLE
Numbers for NER

### ISSUE THREAD

**Issue by Amphagory** [zalandoresearch/flair#492]
I was wondering what I should give Flair for the representation of a date (02/12/19 B-DAT) or an address (123 B-ADD My I-ADD Street I-ADD) for training on my own corpus.

OR 

Removing the numbers so it doesn't learn upon them like, ##/##/## B-DAT?

**Comment by alanakbik** [comment]
Hi @Amphagory are you training a model or are you using a pre-trained model over your data? 

We generally don't do any preprocessing at all, just take the text as-is since the character level language models can typically deal with any type of text.

**Comment by Amphagory** [comment]
Hi @alanakbik,

I'm training own NER model for invoice.  Want it to predict addresses, currency, dates, times, etc...

Normally, I would replace numbers with say 0 (i.e. '$16.88' would become '$00.00' or '123 my street' would become '000 my street') such that the model would not train on specific numbers.

I guess you are saying that is not the case for Flair or maybe it did some behind the scene processing?

**Comment by alanakbik** [comment]
Hi, yes in that case each embedding has its own handling of unknown numbers. Most embeddings will take the numbers as-is - for instance our `FlairEmbeddings` - and some embeddings will replace numbers with 0s, such as the `WordEmbeddings('glove')`. Since our recommended embedding configuration is a stack of Flair and GloVe embeddings (see [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md#recommended-flair-usage)), a bit of both will happen :)

This means that I would suggest not to do any preprocessing yourself and just use the data as it is. As an additional experiment, you could also do another training run in which you replace all numbers with zeros - I'd be interested to hear if that makes a difference.

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen to share results or if you have more questions!
