### ISSUE TITLE
Adding features for tokens in Sentence

### ISSUE THREAD

**Issue by MiladAlshomary** [zalandoresearch/flair#618]
Hi,

I have a question on the _Training Sequence Labeling Model_ (tutorial 7) .  I trained my own model on data of the following structure: (two features (the word and its POS) and a tag )

```
the	DT	B-CT
recognition	NN	I-CT
of	IN	I-CT
difference	NN	I-CT
...  ....  ..
... ..... ...
```

Then I wanted to use this model to predict the third column tag. However, in the tutorial the way to do the prediction is as follows:

sentence = Sentence('I love Berlin')
model.predict(sentence)

In this case I don't see how I could add the POS feature for each of the tokens in this sentence. Any idea on how to do this?

Thanks for your help!

**Comment by alanakbik** [comment]
Hello @MiladAlshomary you would need to train a separate model for each type of tag you want to predict. The code in tutorial 7 for instance trains a model on the 'ner' column, thus when you run `predict()` with this model it will predict the 'ner' column. 

You can train an additional model for POS, by setting `tag_type='pos'` in tutorial 7 and saving the model in a different location. Then load both models and use them sequentally, i.e. 

```python
ner_tagger: SequenceTagger = SequenceTagger.load_from_file('path/to/ner/model')
pos_tagger: SequenceTagger = SequenceTagger.load_from_file('path/to/pos/model')

sentence: Sentence = Sentence('George Washington went to Washington .')
ner_tagger.predict(sentence)
pos_tagger.predict(sentence)
```

Hops this clarifies!

**Comment by MiladAlshomary** [comment]
Thanks a lot for the fast reply.

To clarify my question: I am not trying to predict the POS but i want to use it as an extra feature (for each word) in the model. 

I thought that the sequence tagger i trained takes as features the word (its embeddding vector) and its POS tag and outputs the third column. Am I mistaken in this?

**Comment by alanakbik** [comment]
Hello @MiladAlshomary thanks for clarifying - this is currently not default behavior as most classifications are made based on only the text of the sentence but not additional attributes like POS and other tags. In practice, this seems to work well since POS information is implicitly captured by FlairEmbeddings and this removes errors due to false POS tag prediction.

Still, if you want to experiment with using POS tags as features, there is one way to do this currently, but we haven't used it ourselves. It was added in a PR by @tmills a while back - essentially, you define an embedding over POS tags and add this to your stacked embedding. So, your stacked embedding would have a list of word embeddings and include also a POS embedding.

If you check issue #345 and the accompanying PR for more info. Perhaps also @tmills could clarify if you have more questions.

**Comment by MiladAlshomary** [comment]
Hi @alanakbik,

Thanks a lot for your response. I do agree that the POS information is implicitly captured with the embedding. However, I will try also experimenting with adding POS tags as features according to what you suggested.

**Comment by alanakbik** [comment]
Great - please let us know how well it works! I'll close for now, but feel free to reopen if there are more questions / findings.

**Comment by RatulGhosh** [comment]
Hi, 
I training a NER on a custom dataset. The data are coming from documents so along with the token, I'm also using additional features like the x and y coordinates. The data is in the  following format:
`text   x_coordinate    y_coordinate    tag`
I am using OneHotEmbeddings similar to #1542 

During prediction how should I pass those additional features? Any help would be appreciated.
