### ISSUE TITLE
Bug or as-intended: stacked embeddings don't seem to preserve symmetries in the spaces

### ISSUE THREAD

**Issue by ixxie** [zalandoresearch/flair#623]
Embedding can capture semantic parallels as parallels in the vector space, but `StackedEmbeddings` don't seem to preserve this:

```python3
StackedEmbeddings([
    FlairEmbeddings('multi-forward')
])
```

![](https://i.imgur.com/q7ZA7NW.png)

```python3
StackedEmbeddings([
    FlairEmbeddings('multi-forward'), 
    FlairEmbeddings('glove')
])
```

![](https://i.imgur.com/uTLFNOr.png)

Is this working as intended? I can imagine its not trivial to make a `StackedEmbedding` that preserves these symmetries.

**Comment by alanakbik** [comment]
Hi @ixxie thanks for the question and the visualizations. Generally, this is "as expected" since each embedding space is calculated independently and thus has their own way of capturing semantics. By stacking embeddings, we combine different embeddings into one space and thus allow downstream task models to chose the features of each embedding space that are most useful for a downstream task. This means that symetries are preserved but only in subspaces (which is ok for downstream task training) and not in the full embedding vector.

Hope this clarifies!
