### ISSUE TITLE
[Language Model Training] Epoch selection vs early exit

### ISSUE THREAD

**Issue by TDaudert** [zalandoresearch/flair#669]
Hi,

since it is possible to stop training at any point (early exit), I'd like to know whether there are any pros and cons of this option over selecting the right number of epochs?
For example, one could just set the epochs to 50 and stop training if the loss is acceptable. Contrary, we can't increase the number of epochs during training when realising that the set number is not sufficient.

**Comment by alanakbik** [comment]
Hi @TDaudert setting a maximum number of epochs when executing an annealing strategy is generally a good way if you have limited computational bugdet. For instance, often times you want to try out different parameter combinations but have limited time to do so. In this case, you can set a maximum number of epochs to 50, 100 or 150 to speed up computation and take the combination that works best on validation data. The tradeoff here is that if you limit to 50 epochs, you can try out more combinations than if you limit to 150. However, the results after 150 epochs may be more significant since this gives more time for annealing to complete. So the pros and cons are that you are trading off more but less dependable data points with fewer more significant ones.

**Comment by TDaudert** [comment]
Hi @alanakbik
thanks for your response. If I understand correctly, the annealing strategy would be affected by early exiting training.
So let me re-phrase my question:
Is there any difference between a model which is trained with 5 epochs (set up front) vs one trained with 5 epochs but early exited (10 epochs set up front)?

**Comment by alanakbik** [comment]
If I understand correctly, there is no difference: the max epochs has no impact on annealing strategy.

**Comment by TDaudert** [comment]
ok, thank you @alanakbik
