### ISSUE TITLE
Flair with Multiple GPU

### ISSUE THREAD

**Issue by Dhanachandra** [zalandoresearch/flair#725]
A clear and concise description of what you want to know.

**Comment by alanakbik** [comment]
Partially answered in #731 so closing this issue for now: For 0.4.2 Multi-GPU support is unlikely, since we have problems with GPU utilisation we want to look into first before adding more GPUs. The only part of the code that is ready for multi-GPU now is the language model training part since it already uses DataLoaders and has 100% GPU utilization. But 0.4.2 will add PyTorch DataLoaders for classification and sequence labeling datasets, so it will prepare multi-GPU support in the future.
