### ISSUE TITLE
Fine-tune certain embeddings, but not others

### ISSUE THREAD

**Issue by carolmanderson** [zalandoresearch/flair#789]
From other discussions, I understand the token embeddings aren't trainable here, but a similar effect is achieved via a fully-connected layer on top of the embeddings.

I am using both glove embeddings and flair embeddings, and would like the glove embeddings to remain completely frozen, while allowing the flair embeddings to be projected. In other words, I want the fully-connected layer to apply only to the output of the flair embeddings. What would be the most straightforward way to achieve this?

**Comment by alanakbik** [comment]
Hello @carolmanderson - that is a good question. The framework currently does not support a per-embedding finetuning option, but this is something we'd like to add at some point (and in fact something that people have asked for in previous issues). There are a lot of questions attached however how to best fit this in the framework and how not to confuse users with too many options. While I think this will eventually be added I cannot say when since this will require a bunch of changes. 

In the meantime, the 'simplest' way to do this would be to set `reproject_words` to `False` in the `SequenceTagger` so that nothing gets reprojected. Then, you could make a copy of the `FlairEmbeddings` class and name it `FlairEmbeddingsFineTune` or so, and add the extra linear layer to the `_add_embeddings_internal()` method. You could run your experiment with the `FlairEmbeddingsFineTune` class to achieve this effect. Hope this helps!

**Comment by carolmanderson** [comment]
Thank you for the comments and suggestion. That is helpful!

**Comment by alanakbik** [comment]
Great, let us know if you have any interesting results / more questions!

**Comment by hongjiedai** [comment]
> SequenceTagger

Dose `SequenceTagger` support the parameter `reproject_words`?
I didn't find it in the source code but only in  `DocumentRNNEmbeddings`

**Comment by alanakbik** [comment]
@hongjiedai yes it is enabled by default through the variable `self.relearn_embeddings` of the `SequenceTagger`.

**Comment by hongjiedai** [comment]
Roger that. Thank you
