### ISSUE TITLE
train bi-directional LM together

### ISSUE THREAD

**Issue by Icyzrw** [zalandoresearch/flair#812]
Hi，good project!
I would like to know why flair choose to train different direction LM seperately rather than a bi-LSTM language model at a time. 
Thanks a lot ~

**Comment by alanakbik** [comment]
Hi @Icyzrw it has to be done this way since in language models you are either always predicting the next character on the basis of previous characters (forward LM), or read the sentence backwards and try to predict the previous character based on all next characters (backward LM). It's not possible to do both at the same time since then you would already see the next character which would be trivial to predict.

**Comment by Icyzrw** [comment]
Oh, I see. Thanks a lot ~
