### ISSUE TITLE
How to stop reducing learning rate?

### ISSUE THREAD

**Issue by Aditya715** [zalandoresearch/flair#849]
Learning rate goes down and training quit at a minimum learning rate, it doesn't allow me to restart training from checkpoints. If I try to do so the learning rate create a issue. I don't want to reduce my learning rate as I train small amount daily

**Comment by alanakbik** [comment]
Hello @Aditya715 the learning rate annealing is controlled through the `patience` parameter, which by default is set to 3. This means that the learning rate will anneal if three epochs without any improvement are encountered. You could for instance increase this parameter so that annealing does not happen so often. 

Otherwise, you could try overriding the learning rate of the optimizer of the model you've restored from a checkpoint. I think this should work:

```python
trainer: ModelTrainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)
learning_rate = 0.1
for param_group in trainer.optimizer.param_groups:
        param_group['lr'] = learning_rate
```

**Comment by Aditya715** [comment]
Thanks for helping me out @alanakbik

**Comment by jasminesjlee** [comment]
A question about this -- it looks like the patience defines the number of splits after which the learning rate will anneal. So, if I have 100 splits and three splits pass without any improvement, then the learning rate is annealed. Is this supposed to happen? Or is it supposed to be three epochs?

**Comment by alanakbik** [comment]
Hi @jasminesjlee the definition of patience unfortunately differs slightly between the `ModelTrainer` and the `LanguageModelTrainer`: 

In the `ModelTrainer`, patience refers to the number of epochs (i.e. passes over the complete training data) that it waits without improvement until the learning rate anneals. This is the standard definition which is why we use it for most tasks. 

In the `LanguageModelTrainer` however, patience refers to the number of training data splits without any improvement. We did this because training data for training language models is typically huge and divided into 20-100 splits. So this allows for more fine-grained control of annealing. We generally advise setting patience to about half the number of splits. So if you have 100 training splits, you could set patience to 50 or even lower (25-30) if you don't have so much time. But setting patience to a very low value such as 3 will probably cause the model to anneal too quickly. 

Hope this clarifies!

**Comment by jasminesjlee** [comment]
Oh, this makes sense. Thank you very much!

**Comment by DecentMakeover** [comment]
@alanakbik 

trainer: ModelTrainer = ModelTrainer.load_from_checkpoint(checkpoint, corpus)
	learning_rate = 0.1
	for param_group in trainer.optimizer.param_groups:
	        param_group['lr'] = learning_rate

I dont this works, when i try this i get 

  File "fine_tune.py", line 72, in <module>
    for param_group in trainer.optimizer.param_groups:
AttributeError: type object 'SGD' has no attribute 'param_groups'
