### ISSUE TITLE
Simple one-hot encoding at characters-level in a sentence/document

### ISSUE THREAD

**Issue by wagglefoot** [zalandoresearch/flair#862]
I was wondering if it would be possible to add simple one-hot encoding of characters in a sentence. You already provide the following method, but this still requires training on a down-stream task:
```
from flair.embeddings import CharacterEmbeddings

# init embedding
embedding = CharacterEmbeddings()

# create a sentence
sentence = Sentence('The grass is green .')

# embed words in sentence
embedding.embed(sentence)
```

I am looking for the good old and simple one-hot encoding where the above example would then take the form:
```
# init embedding
embedding = OneHotCharacterEmbedding()

# create a sentence
sentence = Sentence('The grass is green .')

# embed CHARACTERS in sentence
embedding.embed(sentence)

>>>the output of the embedding is that each character in sentence gets embedded in a d-dimensional space as usual, where d is 100 for example.
```

Has this already been done somewhere? I know there is a one-hot encoding of words available, but I cannot find anything for the individual characters. Any advise would be most welcome on a) its existence b) how to go about doing it.

[For aid of exposition, keras does it this way](https://datascience.stackexchange.com/questions/31141/one-hot-encoding-at-character-level-with-keras). 

Thx!

**Comment by alanakbik** [comment]
Hi @wagglefoot the interface is currently designed in such a way that each embeddings class must return a token or document-level embedding. So the `CharacterEmbeddings` class does partly what you want: It first does a one-hot encoding of characters in each word, but then additionally runs a RNN over these characters to get a word-level representation. 

Note that any one hot embedding layer requries training on a downstream task to make sense. So even without the RNN (for instance the word-level one hot encoded embeddings) require a downstream task so that the map from one hot to dense vector is learned in such a way that it makes sense. 

Could you tell us more about your use case? We're currently only looking at word and document level embeddings since that services most use cases, but I could see us expanding to other granularities if there are good use cases for it.

**Comment by wagglefoot** [comment]
Hi @alanabik, I want to use flair to do character level language modelling, specifically sentence classification a la https://arxiv.org/abs/1602.02410 or https://arxiv.org/abs/1509.01626 (I know flair doesn't do convolutions yet). 

Essentially I want to be able to use character level embeddings (one hot) and pass them to flairs LSTM sequence modeller.

Thx

**Comment by alanakbik** [comment]
Sounds interesting! We don't yet fully support this, but you could have a look at the `LanguageModel` class and specifically the `get_representation()` method which returns a tensor with all hidden states for each character in a string. With this method, you can get pretrained representationf for each character and then use a standard PyTorch LSTM on top.

**Comment by alanakbik** [comment]
Closing for now, but feel free to reopen if you have more questions.
