### ISSUE TITLE
Adding tensorboardX for realtime visualization

### ISSUE THREAD

**Issue by felicitywang** [zalandoresearch/flair#923]
Would you consider adding support for TensorBoard? [tensorboardX](https://github.com/lanpa/tensorboardX) is very easy to use. Or APIs from the trainer to add values to tensorboardX. This would allow visualization for real time or for multiple experiments together.

**Comment by alanakbik** [comment]
This looks interesting. Would you be interested in doing a PR for this?

**Comment by stefan-it** [comment]
Hi,

I made a first draft, implementation is very easy. Since PyTorch 1.1.0 the TensorBoardX implementation is included, so it can be imported with `from torch.utils.tensorboard import SummaryWriter`.

Here's a screenshot of for training a model with Flair:

![image](https://user-images.githubusercontent.com/20651387/61735923-4caa5e00-ad85-11e9-917c-a65f3d152e56.png)

**Comment by felicitywang** [comment]
Thanks for the commit and quick response. Helped with my modifications. 

Not going to create a PR as my needs quite specific and some hard-coded. Pasting my modifications here though in case someone's interested in some reference(tensorboard and config.ini): https://github.com/felicitywang/flair/commit/c2876af28f24a58944f49af155a5468d4910b783


Closing?

**Comment by alanakbik** [comment]
@felicitywang thanks for sharing your modifications. @stefan-it added a first PR for this and we hope this with more tensorboardX features in the future! Closing for now, but feel free to reopen if you have more comments / questions.
