### ISSUE TITLE
HashTag ignored for Column Corpus

### ISSUE THREAD

**Issue by ZihanWangKi** [zalandoresearch/flair#940]
**Describe the bug**
When reading from a ColumnCorpus, lines with hash tags are ignored. This may bring problems to tasks such as Wnut17(there are hash tags at start of words.)
See https://github.com/zalandoresearch/flair/blob/b0e4cc1a92c4bd56536ed4e09c8ff6cb1a89f08c/flair/datasets.py#L424

**To Reproduce**
Run NER experiment with Wnut17.

**Expected behavior**
Hash-tag-starting words should be kept.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: linux
 - Version [e.g. flair-0.3.2]: flair-0.4.2

**Additional context**

**Comment by alanakbik** [comment]
@ZihanWangKi thanks for spotting this - I can reproduce the error. Hash tags are used in CoNLL-U datasets to [denote comments](https://github.com/UniversalDependencies/docs/issues/642), which is why we currently ignore lines that begin with them. 

However, you're right that we need special rules for some datasets such as WNUT where a line that begins with a hash tag is just a word. Will put in a PR for this!
