### ISSUE TITLE
Dev data loaded as test data

### ISSUE THREAD

**Issue by anjapago** [zalandoresearch/flair#951]
**Describe the bug**
The dev data is being loaded into the test data.
Due to this line in the code: https://github.com/zalandoresearch/flair/blob/b0e4cc1a92c4bd56536ed4e09c8ff6cb1a89f08c/flair/datasets.py#L319

**To Reproduce**
Use the CSVClassificationCorpus to load test, train and dev data from csv.

**Expected behavior**
The test.csv should be loaded into corpus.test

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]:
 - Version [e.g. flair-0.3.2]:

**Additional context**
Could be related to this question: https://github.com/zalandoresearch/flair/issues/947

**Comment by BernierCR** [comment]
Awesome, I pretty much suspected this was happening. More evidence, the dev and test sets have the same scores/loss. Dev is being loaded twice. This would probably also explain when it complains about not being able to find the test loss. 

Since this is so easy to fix, could you please just fix it in master ASAP? 

Thanks anjapago for tracking down the actual problem. I haven't gotten around to tracking it down at this level yet.

**Comment by anjapago** [comment]
It’s fixed in my fork but I have another change already in there so I shouldn’t merge it directly yet. I’m not sure if there’s a way to just select one commit to merge in github? Otherwise, I’ll undo my other change then merge.

**Comment by alanakbik** [comment]
Fixed in #952 - thanks @anjapago!
