### ISSUE TITLE
Input format for the language model

### ISSUE THREAD

**Issue by iamyihwa** [zalandoresearch/flair#96]
Hello, 
I have been reading the tutorials, but I haven 't found a clear guideline with regards to the format of the language model training input. 

What I am not very sure about is whether it is okay to provide: 

(1) The grass is green. 

or I need to do 
(2) The grass is green . 

From[ the tutorial on the basic types ](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_BASICS.md), it seems both (1)  and (2) can be received.

**Comment by alanakbik** [comment]
Hello @iamyihwa - very good point and something we need to clarify in the documentation! The language model training code takes a text file "as is". That means that if it is not tokenized it does not perform tokenization. That is how we want it, since the language model works at the character level and we want to model the language without any NLP preprocessing. 

That said, in practice we found that there is little difference whether you train on untokenized or whitespace tokenized data. The billion word corpus for instance is already tokenized, so the English 'news' LMs were trained over tokenized data, while the other ones were trained over untokenized data. Both seem to work well - though we have to run more experiments to quantify the exact difference. 

So our suggestion would be not to tokenize the data.

**Comment by iamyihwa** [comment]
Thanks @alanakbik for the clarification. I will then use non-tokenized version (1) , such that punctuations and commas are not separated from the word.
